### PR TITLE
Fix bug where multiline text in toast messages had incorrect vertical padding

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Review by ScopeyNZ — CHANGES_REQUESTED** [review]
I assume this is unintentional:

image

**Comment by robbieaverill** [comment]
The escaping or the button being on the right? Storybook escapes HTML by default

**Comment by robbieaverill** [comment]
Updated

**Review by ScopeyNZ — APPROVED** [review]
Hawt

**Pull request merged**
