### PR TITLE
ChecDropdown no longer accepts value attributes that do not exist in the options attribute

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes https://github.com/chec/ui-library/issues/190

### CODE REVIEW

**Review by ScopeyNZ — APPROVED** [review]

**Comment by ScopeyNZ** [comment]
On second thought, the way this is written it'll only throw an error when the component is created, and not if you bind in an invalid value after it's mounted...

**Comment by robbieaverill** [comment]
Correct, there's no way to do that

**Comment by robbieaverill** [comment]
Well I suppose there is a way to do that but I feel like it's unlikely to happen

**Comment by ScopeyNZ** [comment]
Yeah the only way is to set up a watch... This is really a tool to help developers not foot-gun, so I'm happy as is.

**Pull request merged**
