### PR TITLE
Add customers and account icons to nav icons

### PR DESCRIPTION
**Pull request by jaepass**

### CODE REVIEW

**Review by robbieaverill — APPROVED** [review]
Are the white borders in the icons deliberate?

**Comment by jaepass** [comment]
Heyhey yes are they are, meant for white space

**Comment by jaepass** [comment]
hm yea hold up actually, I'll subtract the white space instead of having white borders

**Comment by jaepass** [comment]
Got rid of white borders, nice catch thank you!

**Review by ScopeyNZ — APPROVED** [review]

**Pull request merged**
