### PR TITLE
Update hologram background and add parallax directive

### PR DESCRIPTION
**Pull request by ScopeyNZ**
Side effect here is that we remove the unnecessary and huge `bg-hologram.png` from our bundle.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Hmmmn the accelerometer stuff is a bit janky.

**Comment by ScopeyNZ** [comment]
FYI for the accelerometer stuff - it works, it's not buggy. "Janky" just means that sometimes the hologram effect jumps a bit if you orient your phone in a certain direction. I could probably tweak it some more, but I'm not very good at the maths involved.

**Comment by jaepass** [comment]
This is sweet can't wait to see it implemented!

**Review by jaepass — APPROVED** [review]

**Comment by jaepass** [comment]
I see what you mean with the slight jump on touch too but I don't think that's a huge issue. Looks great otherwise on desktop!

**Pull request merged**
