### PR TITLE
Removing hover, focus and active from tags

### LINKED ISSUE #555: ChecTag: should not have a hover state unless it is interactive
The ChecTag component has a hover state where it switches from light to dark (with default props). It shouldn't do this because clicking on the tag does nothing by default.

### PR DESCRIPTION
**Pull request by kvisca**
Realized that this isn't actually a button so I removed the hover states outright. Issue confused me but I can't find an instance where these are clickable as a router link. 

Closes #555

### CODE REVIEW

**Comment by robbieaverill** [comment]
I think the blog post in the marketing site uses them as links. We could refactor this to use tags.

**Comment by kvisca** [comment]
@robbieaverill yea that's weird, they're just wrapped in a link. I'm going to make a button-type tag and replace it. PR incoming.

**Comment by kvisca** [comment]
Opened PR fixing in chec/marketing-chec#714

**Review by robbieaverill — APPROVED** [review]
LGTM, there's an "active" knob in one of the tag stories that could be removed as well if you want to delete it

**Comment by robbieaverill** [comment]
cc @kvisca

**Comment by kvisca** [comment]
@robbieaverill sorry about that, I'll update that right now.

**Review by robbieaverill — APPROVED** [review]

**Pull request merged**
