### PR TITLE
add active class to heading to conditionally remove pb when active

### PR DESCRIPTION
**Pull request by jaepass**
should fix https://github.com/chec/dashboard/issues/274

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Comparing the deploy preview and the current state:

https://deploy-preview-295--chec-ui.netlify.app/?path=/story/components-accordion--default-story
https://chec-ui.netlify.app/?path=/story/components-accordion--default-story

I feel like it looks a bit off now.

**Comment by jaepass** [comment]
hmm yea im not sure why the ui component has a fixed height regardless of whether theres a subtitle or not. in implementation would look like this when accordion is inactive:
Screen Shot 2020-09-18 at 2 57 46 PM
and when active:
Screen Shot 2020-09-18 at 2 58 04 PM

**Comment by ScopeyNZ** [comment]
Yeah okay I've had a brief look at this and something really weird is happening here. There's a helpful resource I found:

https://medium.com/fed-or-dead/margin-collapse-or-why-your-child-element-is-moving-the-parent-b199a0b60497

**Comment by jaepass** [comment]
ok thanks will take a look at that!

**Comment by robbieaverill** [comment]
Feel free to reopen when this is ready for review

**Comment by jaepass** [comment]
Thanks, sorry haven't come back to this but will do so.

**Pull request closed without merging**
