### PR TITLE
Refactor label to not cover half the input

### PR DESCRIPTION
**Pull request by ScopeyNZ**
The problem was that the label was actually covering half the input, and we were using a `:before` psuedo-element to actually render the text. I couldn't figure out why we did this, so I've refactored it to use the actual label, and made it only as big as it's contents. I also fixed up the alignment so that it's correctly aligned with the text field value.

Fixes chec/dashboard#53

### CODE REVIEW

**Comment by robbieaverill** [comment]
Does this mean we don't need `{force: true}` in Cypress anymore?

**Comment by robbieaverill** [comment]
Multiline is funky
image

**Comment by robbieaverill** [comment]
Otherwise looking good

**Comment by john-raymon** [comment]
Nice, this doesn't https://github.com/chec/ui-library/issues/158#issuecomment-663280963 right

**Comment by ScopeyNZ** [comment]
Nope it doesn't solve that issue. That'd require some JS changes I assume.

**Comment by john-raymon** [comment]
Changing `margin: 1px;` to `padding: 1px;` on line 328 seems to fix the funky multiline bug. https://github.com/chec/ui-library/blob/f63619e2a0befdcc115f8e93bded180b7a674463/src/components/TextField.vue#L328

**Comment by ScopeyNZ** [comment]
There was more to it than that. The underlay was broken.

**Comment by ScopeyNZ** [comment]
It should fix the `{force:true}` hack in dash yeah.

**Pull request merged**
