### PR TITLE
Updating accordion styles

### PR DESCRIPTION
**Pull request by kvisca**
Updating the accordion styling to match updated designs. 

Screen Shot 2020-12-11 at 1 54 55 PM

### CODE REVIEW

**Review by robbieaverill — APPROVED** [review]
Is that story you deleted no longer relevant?

**Comment by kvisca** [comment]
> Is that story you deleted no longer relevant?

Correct. I did the changes with Blaze and moving forward we won't be using that design pattern.

**Comment by ScopeyNZ** [comment]
Just chiming in here - that story may not have been a real world use case, but was highlighting issues with margin collapsing that came up at one point. The story was probably still relevant to illustrate that issue that might occur.

**Comment by kvisca** [comment]
> Just chiming in here - that story may not have been a real world use case, but was highlighting issues with margin collapsing that came up at one point. The story was probably still relevant to illustrate that issue that might occur.

I'll put in a PR to add it back in then.

**Pull request merged**
