### PR TITLE
[CHEC-1094]Thumbnail Card

### PR DESCRIPTION
**Pull request by kvisca**
Adding thumbnail card component.

@dvnkshl @blazepollard I took some liberties when putting this component together due to the time restraint and need for light variants. Let me know if anything needs to be tweaked. 

**Light Variant:**
Screen Shot 2020-12-13 at 6 01 29 PM

**Dark Variant:**
Screen Shot 2020-12-13 at 6 01 34 PM

**Fallback:**
Screen Shot 2020-12-13 at 6 03 20 PM

### CODE REVIEW

**Comment by dvnkshl** [comment]
Is this for this thumbnail card? https://www.figma.com/file/og79WKi1zrrBgZWayZY4ik/Dashboard---Web?node-id=7128%3A0
image

**Comment by kvisca** [comment]
> Is this for this thumbnail card?

It will be yes.

**Comment by blazepollard** [comment]
@kvisca 
Looks good to me 👍

**Comment by dvnkshl** [comment]
Don't think the toggle/switch works for this one, any way we can add a hidden radio toggle option which adds the "selected" border to the card? (Or is that more of a concern for the dashboard code base?) - and can we default the green button to gray?

**Comment by dvnkshl** [comment]
Also smaller thing, border radius is showing on the top of the bottom card image

**Comment by kvisca** [comment]
> Don't think the toggle/switch works for this one, any way we can add a hidden radio toggle option which adds the "selected" border to the card? (Or is that more of a concern for the dashboard code base?) - and can we default the green button to gray?

This component lets you pass anything into the grey part. That was just an example to show what could be passed. The integrated version would match the design (there is another PR for the rounded checkbox).

**Review by ScopeyNZ — APPROVED** [review]

**Pull request merged**
